### ISSUE TITLE
Suggestion url to use template is broken

### ISSUE THREAD

**Issue by slamer59** [mirumee/saleor-app-framework-python#43]
Hello,
the repo disapear ? 
In the readme
https://github.com/mirumee/saleor-app-template

**Comment by slamer59** [comment]
In the documentation : 
https://github.com/mirumee/saleor-app-framework-python/tree/main/samples

**Comment by lacosteque** [comment]
It is sad :(

**Comment by pkucmus** [comment]
You can checkout the older https://github.com/mirumee/saleor-app-framework-python/tree/0.2.6/samples, we might switch to something else in the near future. Don't expect this project to receive much love.

**Comment by pkucmus** [comment]
The the "app framework" is now replaced by https://github.com/mirumee/saleor-sdk-python.
